name: PR

on:
  push:
    branches:
      - master # Run on pushes to the master branch
  pull_request:
    branches:
      - master # Run on pull requests targeting the master branch
  workflow_dispatch: # Allow manual triggering of the workflow

permissions:
  contents: read

jobs:
  run-tests:
    name: Run unit and integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java 11
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '11'

      - name: Test with Ant
        run: |
          java --version
          ant -version
          ant clean build \
            unit-test \
            integration-test